export const dummyData = [
    {
        id: 1,
        judul: 'test1',
        content: 'content1',
        created_at: '12 Mei 2022',
        created_by: 'Admin 1',
        updated_at: '13 Mei 2022',
        updated_by: 'Admin 2',
        updated_at: '15 Mei 2022',
        updated_by: 'Admin 3',
    },
    {
        id: 2,
        judul: 'test2',
        content: 'content2',
        created_at: '12 Mei 2022',
        created_by: 'Admin 1',
        updated_at: '13 Mei 2022',
        updated_by: 'Admin 2',
        updated_at: '15 Mei 2022',
        updated_by: 'Admin 3',
    },
    {
        id: 3,
        judul: 'test3',
        content: 'content3',
        created_at: '12 Mei 2022',
        created_by: 'Admin 1',
        updated_at: '13 Mei 2022',
        updated_by: 'Admin 2',
        updated_at: '15 Mei 2022',
        updated_by: 'Admin 3',
    },
]